export {
    BANKCARD_PAGE_PATH,
    CONTACTS_PAGE_PATH,
    HOME_PAGE_PATH,
    INITIAL_PATH,
    TIMELINE_PAGE_PATH,
    OTHER_PATH,
    IDEAS_PAGE_PATH,
    SERVICE_PAGE_PATH,
    MARKET_PAGE_PATH,
    STREAMS_PAGE_PATH,
    SPARKS_PAGE_PATH,
    SNAPS_PAGE_PATH,
} from "@/routes/constants/constants";
