import { BanksDataType } from "@/services/BankApiService/BankApiService";

export const mockMapData: BanksDataType[] = [
    {
        name: "Belinvestbank",
        city_type: "",
        city: "Vitebsk",
        gps_x: "55.161547",
        gps_y: "30.219956",
        color: "",
        address_type: "",
        address: "Voinov-Internationalists Street",
        house: "23-75",
        currency: "CAD",
    },
    {
        name: "VTBBank",
        city_type: "",
        city: "Vitebsk",
        gps_x: "55.181738",
        gps_y: "30.210926",
        color: "",
        address_type: "",
        address: "Moskovsky avenue",
        house: "16",
        currency: "BTC CAD YEN JPY AUD",
    },
    {
        name: "BankDabrabyt",
        city_type: "",
        city: "Vitebsk",
        gps_x: "55.191429",
        gps_y: "30.203732",
        color: "",
        address_type: "",
        address: "Lenina street",
        house: "26A",
        currency: "BTC CAD YEN JPY AUD",
    },
    {
        name: "BankDabrabyt",
        city_type: "",
        city: "Vitebsk",
        gps_x: "55.190655",
        gps_y: "30.205354",
        color: "",
        address_type: "",
        address: "Lenina street",
        house: "26/2",
        currency: "CAD AUD",
    },
    {
        name: "MTBank",
        city_type: "",
        city: "Vitebsk",
        gps_x: "55.18983",
        gps_y: "30.205929",
        color: "",
        address_type: "",
        address: "Lenina street",
        house: "17",
        currency: "CAD",
    },
    {
        name: "BankDabrabyt",
        city_type: "",
        city: "Vitebsk",
        gps_x: "55.193267",
        gps_y: "30.225014",
        color: "",
        address_type: "",
        address: "Frunze Avenue",
        house: "35/1",
        currency: "BTC CAD",
    },
    {
        name: "Belinvestbank",
        city_type: "",
        city: "Vitebsk",
        gps_x: "55.19388",
        gps_y: "30.191103",
        color: "",
        address_type: "",
        address: "Kirova Street",
        house: "7-76",
        currency: "CAD EUR",
    },
    {
        name: "Belgazprombank",
        city_type: "",
        city: "Vitebsk",
        gps_x: "55.17244",
        gps_y: "30.202728",
        color: "",
        address_type: "",
        address: "Stroiteley Avenue 1g",
        house: "1g",
        currency: "CNY EUR",
    },
    {
        name: "Priorbank",
        city_type: "",
        city: "Vitebsk",
        gps_x: "55.170973",
        gps_y: "30.21521",
        color: "",
        address_type: "",
        address: "Stroiteley Avenue",
        house: "11а",
        currency: "BTC YEN JPY EUR",
    },
];
